# syntax=docker/dockerfile:1.4
FROM node:18

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm install

RUN npm install -g nodemon

# Do NOT copy source code here
# Source will be mounted from host

EXPOSE 3847
CMD ["nodemon", "--legacy-watch", "src/index.js"]
